export ESP_DIR := "target/esp"
export BOOT_DIR := ESP_DIR/"efi/boot"

start:
    cargo build

    rm -rf $BOOT_DIR
    mkdir -p $BOOT_DIR

    ln -s $(realpath target/x86_64-unknown-uefi/debug/exokernel.efi) \
        $BOOT_DIR/bootx64.efi

    qemu-system-x86_64 -enable-kvm \
        -drive if=pflash,format=raw,readonly=on,file=$OVMF_PATH/OVMF_CODE.fd \
        -drive if=pflash,format=raw,readonly=on,file=$OVMF_PATH/OVMF_VARS.fd \
        -drive format=raw,file=fat:rw:$ESP_DIR \
